version: "3.9"

services:
  app:
    build:
      context: .
    container_name: streamlit-template
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8501}:8501"
    volumes:
      - ./app:/app
      - ${SNOWFLAKE_PRIVATE_KEY_PATH}:/run/secrets/rsa_key.p8:ro
    command: ["streamlit", "run", "streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8501"]


